version: '3.4'

services:
  udemynewmicroservice.catalog.api:
    image: ${DOCKER_REGISTRY-}udemynewmicroservicecatalogapi
    build:
      context: .
      dockerfile: UdemyNewMicroservice.Catalog.API/Dockerfile
