@baseAddress = https://localhost:7037

GET {{baseAddress}}/api/categories
Accept: application/json

###

GET {{baseAddress}}/api/categories/9
Accept: application/json



###

POST {{baseAddress}}/api/categories
Accept: application/json
Content-Type: application/json

{
  "name": "Category 1"
}

###
